pub mod statement_typer;

use crate::structs::StatementConfig;
use once_cell::sync::Lazy;
use std::collections::HashMap;

pub use statement_typer::StatementTyper;

// The build script (build.rs) emits generated_configs.rs into OUT_DIR; include it here.
include!(concat!(env!("OUT_DIR"), "/generated_configs.rs"));

/// Global registry of all compiled / loaded statement configurations.
/// Keys are the `key` field inside each `StatementConfig`.
pub static STATEMENT_CONFIG_REGISTRY: Lazy<HashMap<String, StatementConfig>> = Lazy::new(|| generated_configs());

/// Fetch a config by key.
pub fn get_config(key: &str) -> Option<&'static StatementConfig> {
	STATEMENT_CONFIG_REGISTRY.get(key)
}

/// List all config keys.
pub fn list_config_keys() -> Vec<&'static str> {
	STATEMENT_CONFIG_REGISTRY.keys().map(|k| k.as_str()).collect()
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_registry_contains_cba() {
		// Should load from embedded JSON via include_str! generated by build.rs
		let cfg = get_config("au__cba__credit_card__1").expect("cba config missing");
		assert_eq!(cfg.key, "au__cba__credit_card__1");
	}
}
